function medicasoft(){var P='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',ac='&',rc='.cache.html',_='/',lb='//',qc=':',pb='::',Ac='<script defer="defer">medicasoft.onInjectionDone(\'medicasoft\')<\/script>',hb='<script id="',sb='=',$='?',ub='Bad handler "',zc='DOMContentLoaded',pc="GWT module 'medicasoft' may need to be (re)compiled",jb='SCRIPT',dc='Unexpected exception in locale detection, using default: ',cc='_',bc='__gwt_Locale',gb='__gwt_marker_medicasoft',Xb='adobeair',Yb='air',kb='base',cb='baseUrl',T='begin',S='bootstrap',Db='chrome',bb='clear.cache.gif',rb='content',yc='css/chart.css',$b='en',Y='end',Tb='gecko',Vb='gecko1_8',Wb='gecko1_9',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',sc='gwt/clean/clean.css',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',Cb='gxt.user.agent',xc='head',nc='hosted.html?medicasoft',wc='href',Hb='ie6',Jb='ie7',Lb='ie8',Mb='ie9',yb='iframe',ab='img',zb="javascript:''",tc='link',ic='linux',mc='loadExternalRefs',Zb='locale',_b='locale=',hc='mac',gc='mac os x',fc='macintosh',Q='medicasoft',eb='medicasoft.nocache.js',ob='medicasoft::',mb='meta',Bb='moduleRequested',X='moduleStartup',Fb='msie',Gb='msie 6',Ib='msie 7',Kb='msie 8',nb='name',Eb='opera',Ab='position:absolute;width:0;height:0;border:none',uc='rel',Ub='rv:1.8',Nb='safari',Pb='safari3',Rb='safari4',Sb='safari5',db='script',oc='selectingPermutation',R='startup',vc='stylesheet',fb='undefined',lc='unknown',ec='user.agent.os',Ob='version/3',Qb='version/4',kc='win32',jc='windows';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=P,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(Q);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return H(a)}}medicasoft=null;c.gwtOnLoad(z,Q,t,y);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function D(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=G(cb);if(a!=null){return a}return P}
function h(){var a=n.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;n.write(hb+b+ib);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=n.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
function k(){var a=n.location;return a.href==a.protocol+lb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==P){l=h()}if(l==P){l=i()}if(l==P){l=j()}if(l==P&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,P);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,i=g.indexOf(sb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a,b){return b in v[a]}
function G(a){var b=u[a];return b==null?null:b}
function H(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=n.createElement(yb);a.src=zb;a.id=Q;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+L)}}
w[Cb]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Db)!=-1)return Db;if(a.indexOf(Eb)!=-1)return Eb;if(a.indexOf(Fb)!=-1){if(a.indexOf(Gb)!=-1)return Hb;if(a.indexOf(Ib)!=-1)return Jb;if(a.indexOf(Kb)!=-1)return Lb;return Mb}if(a.indexOf(Nb)!=-1){if(a.indexOf(Ob)!=-1)return Pb;if(a.indexOf(Qb)!=-1)return Rb;return Sb}if(a.indexOf(Tb)!=-1){if(a.indexOf(Ub)!=-1)return Vb;return Wb}if(a.indexOf(Xb)!=-1)return Yb;return null};v[Cb]={air:0,chrome:1,gecko1_8:2,gecko1_9:3,ie6:4,ie7:5,ie8:6,ie9:7,opera:8,safari3:9,safari4:10,safari5:11};w[Zb]=function(){var b=null;var c=$b;try{if(!b){var d=location.search;var e=d.indexOf(_b);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(ac,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=G(Zb)}if(!b){b=m[bc]}if(b){c=b}while(b&&!F(Zb,b)){var h=b.lastIndexOf(cc);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(dc+a)}m[bc]=c;return b||$b};v[Zb]={cr:0,'default':1,en:2,fr:3};w[ec]=function(){var a=m.navigator.userAgent.toLowerCase();if(a.indexOf(fc)!=-1||a.indexOf(gc)!=-1){return hc}if(a.indexOf(ic)!=-1){return ic}if(a.indexOf(jc)!=-1||a.indexOf(kc)!=-1){return jc}return lc};v[ec]={linux:0,mac:1,windows:2};medicasoft.onScriptLoad=function(){if(I){r=true;C()}};medicasoft.onInjectionDone=function(){q=true;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:mc,millis:(new Date).getTime(),type:Y});C()};E();D();var K;var L;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(Q))){m.location.reload();return}L=nc;K=P}o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:oc});if(!B()){try{alert(pc);return;var M=K.indexOf(qc);if(M!=-1){y=Number(K.substring(M+1));K=K.substring(0,M)}L=K+rc}catch(a){return}}var N;function O(){if(!s){s=true;if(!__gwt_stylesLoaded[sc]){var a=n.createElement(tc);__gwt_stylesLoaded[sc]=a;a.setAttribute(uc,vc);a.setAttribute(wc,t+sc);n.getElementsByTagName(xc)[0].appendChild(a)}if(!__gwt_stylesLoaded[yc]){var a=n.createElement(tc);__gwt_stylesLoaded[yc]=a;a.setAttribute(uc,vc);a.setAttribute(wc,t+yc);n.getElementsByTagName(xc)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(zc,O,false)}if(N){clearInterval(N)}}}
if(n.addEventListener){n.addEventListener(zc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(n.readyState)){J();O()}},50);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:mc,millis:(new Date).getTime(),type:T});n.write(Ac)}
medicasoft();